### ISSUE TITLE
Problem initializing a new server

### ISSUE THREAD

**Issue by mfbmina** [fog/fog-softlayer#51]
When i'm try initializing a new server, the os_code attribute is always equal to nil.

```ruby
require 'fog/softlayer'
@sl = Fog::Compute[:softlayer]

opts = {
    :cpu => 2,
    :ram => 2048,       
    :disk => [{'device' => 0, 'diskImage' => {'capacity' => 100 } }],
    :ephemeral_storage => true,
    :domain => "not-my-default.com",
    :name => "hostname",
    :os_code => "UBUNTU_LATEST",
    :datacenter => "ams01"     
 }
 
server = @sl.servers.new(opts)
server.os_code => nil
```

**Comment by cphrmky** [comment]
Confirmed the bug. 

I can get it queued for fixing if you have a need.

I'm wondering why you're doing this at all?
```ruby
  server = @sl.servers.new(opts)
```

You can just do:  
```ruby
  server = @sl.servers.create(opts)
```

At which point, after this returns `true` 
```ruby
  server.ready?
``` 

Then this will be correct:

```ruby
  server.os_code
 #=> "UBUNTU_LATEST"

**Comment by mfbmina** [comment]
Hi @cphrmky ! I was implementing a new request called ["generateOrderTemplate"](http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/generateOrderTemplate) and I wanna be able to get this order template without provision a server and using fog syntax. 

My idea was create a method on Server that uses:
```ruby
remap_attributes(attributes, attributes_mapping)
clean_attributes
````

Using these methods I don't need map all attributes again on "generateOrderTemplate" request!

**Comment by cphrmky** [comment]
@mfbmina, after looking at this a little more closely I'm thinking I don't want to make the changes needed so that you can do it exactly like this, as it would be a hacky workaround at best, and potentially break things at worst (and it would also be a departure form the way the rest of the fog providers work).

Having said that, you should be able to access the `:os_code` and anything else you set in the `opts` hash by doing `server.attributes[:os_code]`.  Does that work for you?

**Comment by mfbmina** [comment]
@cphrmky thanks for the feedback. It works for me!
